### ISSUE TITLE
Test suite started to fail

### ISSUE THREAD

**Issue by eserte** [athreef/WebService-KVV-Live-Stop#1]
See http://matrix.cpantesters.org/?dist=WebService-KVV-Live-Stop%200.005;reports=1#sl=7,1 — currently there are no more PASS reports.

**Comment by a3f** [comment]
Oh, looks like the transportation authority was doing maintenance work both online and in real life.

The website is usable again now and I have updated the failing test to avoid checking the out of order tram connection.

Thanks for the report.
